### ISSUE TITLE
If element is in a non-template scope, but still within a template no template is passed to the events.

### ISSUE THREAD

**Issue by brucejo75** [gwendall/meteor-body-events#6]
If the view does not have a `_templateInstance` the handler is passed `undefined`

Not all views have a `_templateInstance`.  So it is legitimate to walk up the view tree looking for the enclosing `_templateInstance`.

Just need to walk up the view tree [here](https://github.com/gwendall/meteor-body-events/blob/master/lib.js#L20).

**Comment by brucejo75** [comment]
Added [PR#2](https://github.com/gwendall/meteor-body-events/pull/7)

**Comment by gwendall** [comment]
Merged. Thanks !
